### ISSUE TITLE
NodeJS Incompatibility

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Upstra-Q-A#14]
I see an issue with the current package for nodeJS. It says it's incompatible with node 14.15.3 (latest LTS version), says it only works with 14.3. Is it a hard restriction?

**Comment by stevenwangamity** [comment]
@tpark-amity could you please provide more information? like which SDK and which platform? some screenshots would be very helpful

**Comment by y-nk** [comment]
Hello @tpark-amity :)

Thank you for reporting this. As you guess, it's not a hard restriction.
We constantly update our toolchain in order to benefit from the latest optimisations whenever possible.
Nevertheless it should be usable starting from v10.2+.

Let me know if I can be of further assistance.

**Comment by tpark-amity** [comment]
> Hello @tpark-amity :)
> 
> Thank you for reporting this. As you guess, it's not a hard restriction.
> We constantly update our toolchain in order to benefit from the latest optimisations whenever possible.
> Nevertheless it should be usable starting from v10.2+.
> 
> Let me know if I can be of further assistance.

Thank you so much for your response! I'll close this issue for now until there are any further questions.
